language: go
sudo: false
go:
  - tip

install:
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/bosun.org/
  - export GOPATH=$HOME/gopath #Fix gopath. Original has trailing :
  - chmod +x $GOPATH/src/bosun.org/build/validate.sh
  - go get golang.org/x/tools/cmd/vet
  - npm i -g typescript

script: $GOPATH/src/bosun.org/build/build.sh
